name: simple_todo_app
description: A simple To Do App Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: 2.1.1
  logger: 1.3.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  get_test: ^4.0.1
  mocktail: ^0.3.0

flutter:

  uses-material-design: true
